"use client";

import React, { useState } from "react";
import { useDashboard } from "@/components/Dashboard/DashboardContext";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
  SheetFooter
} from "@/components/ui/sheet";
import {
  Inbox,
  Search,
  Mail,
  Phone,
  Calendar,
  User,
  ArrowUpRight,
  CheckCircle2,
  Shield,
  Copy,
  ExternalLink,
  Sparkles,
  Filter
} from "lucide-react";

const LeadsTab = () => {
  const { activeClient, role, leads } = useDashboard();
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedLeadForSheet, setSelectedLeadForSheet] = useState(null);
  const [copiedNotice, setCopiedNotice] = useState(false);

  const clientLeads = role === "client" 
    ? leads.filter((l) => l.clientSlug === activeClient?.slug)
    : leads.filter((l) => l.clientSlug === activeClient?.slug || activeClient?.slug === "egostix-internal");

  const filteredLeads = clientLeads.filter(
    (l) =>
      l.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      l.email.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const handleCopyData = () => {
    if (!selectedLeadForSheet) return;
    const text = `Name: ${selectedLeadForSheet.name}\nEmail: ${selectedLeadForSheet.email}\nPhone: ${selectedLeadForSheet.phone || 'N/A'}`;
    navigator.clipboard.writeText(text);
    setCopiedNotice(true);
    setTimeout(() => setCopiedNotice(false), 2500);
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-200">
      {/* Context Banner */}
      <div className="bg-white rounded-xl border border-neutral-200 p-4 sm:p-6 flex flex-col md:flex-row md:items-center justify-between gap-3 sm:gap-6 shadow-sm">
        <div className="space-y-1 sm:space-y-1.5">
          <div className="flex items-center gap-2">
            <span className="p-1.5 sm:p-2 rounded-lg bg-blue-50 border border-blue-100 text-blue-700 shrink-0">
              <Inbox className="size-4 sm:size-5" />
            </span>
            <h3 className="text-lg sm:text-xl font-mono text-slate-900 font-bold">
              {role === "owner" ? "Global Lead Hub & CRM Pipeline" : "Captured Leads & Inbound Contact Requests"}
            </h3>
          </div>
          <p className="text-xs text-slate-600 max-w-2xl font-inter leading-relaxed">
            Automated lead qualification and CRM record sync generated by Egostix AI concierges and lead capture forms.
          </p>
        </div>
        <div className="flex items-center gap-3 self-start md:self-auto">
          <span className="text-xs font-mono font-bold bg-blue-50 text-blue-700 border border-blue-200 px-3 py-2 rounded-lg">
            Total Leads: {clientLeads.length}
          </span>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="bg-white rounded-xl border border-neutral-200 p-3.5 sm:p-4 shadow-sm flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3">
        <div className="relative flex-1 w-full">
          <Search className="absolute left-3.5 top-3.5 size-4 text-slate-400" />
          <input
            type="text"
            placeholder="Search leads by contact name or email..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 rounded-lg border border-neutral-300 text-xs font-inter focus:border-blue-700 focus:outline-none min-h-[44px]"
          />
        </div>
        <span className="text-xs font-mono text-slate-500 shrink-0 self-end sm:self-auto">
          Showing <strong className="text-slate-900">{filteredLeads.length}</strong> contacts
        </span>
      </div>

      {/* Leads Container (Mobile Cards + Desktop Table) */}
      <div className="bg-white rounded-xl border border-neutral-200 shadow-sm overflow-hidden">
        <div className="p-3.5 sm:p-4 border-b border-neutral-200 bg-neutral-50 flex flex-wrap items-center justify-between gap-2">
          <h4 className="text-xs font-mono font-bold text-slate-900 uppercase tracking-wider">
            Inbound Qualified Contact Records
          </h4>
          <span className="text-[10px] font-mono text-emerald-700 font-bold bg-emerald-50 border border-emerald-200 px-2.5 py-1 rounded-full">
            CRM Sync Active
          </span>
        </div>

        {/* Mobile View: Responsive Lead Cards (Visible on <sm screens) */}
        <div className="block sm:hidden divide-y divide-neutral-100">
          {filteredLeads.length === 0 ? (
            <div className="py-10 px-4 text-center text-slate-400 font-mono text-xs">
              No captured leads found matching query.
            </div>
          ) : (
            filteredLeads.map((lead) => (
              <div
                key={lead.id}
                className="p-4 space-y-3 hover:bg-neutral-50/70 transition"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="flex items-center gap-2.5 min-w-0">
                    <div className="size-8 rounded-full bg-blue-100 border border-blue-200 flex items-center justify-center font-mono font-bold text-xs text-blue-700 uppercase shrink-0">
                      {lead.name.slice(0, 2).toUpperCase()}
                    </div>
                    <div className="min-w-0">
                      <h5 className="font-mono text-xs font-bold text-slate-900 truncate">
                        {lead.name}
                      </h5>
                      <p className="text-[11px] text-slate-500 truncate font-inter">
                        {lead.email}
                      </p>
                    </div>
                  </div>
                  <span className="text-[10px] font-mono text-slate-400 shrink-0">
                    {lead.date || "Recent"}
                  </span>
                </div>

                {lead.notes && (
                  <p className="text-[11px] text-slate-600 font-inter line-clamp-2 bg-neutral-50 p-2.5 rounded border border-neutral-150">
                    {lead.notes}
                  </p>
                )}

                {/* Mobile Direct Action Buttons */}
                <div className="grid grid-cols-3 gap-2 pt-1 border-t border-neutral-100">
                  {lead.phone ? (
                    <a
                      href={`tel:${lead.phone}`}
                      className="flex items-center justify-center gap-1.5 py-2 px-2 rounded-lg bg-emerald-50 hover:bg-emerald-100 text-emerald-700 font-mono text-[11px] font-semibold transition min-h-[40px]"
                    >
                      <Phone className="size-3.5" />
                      <span>Call</span>
                    </a>
                  ) : (
                    <button
                      disabled
                      className="flex items-center justify-center gap-1.5 py-2 px-2 rounded-lg bg-neutral-100 text-slate-400 font-mono text-[11px] min-h-[40px] opacity-60"
                    >
                      <Phone className="size-3.5" />
                      <span>No Tel</span>
                    </button>
                  )}

                  <a
                    href={`mailto:${lead.email}`}
                    className="flex items-center justify-center gap-1.5 py-2 px-2 rounded-lg bg-blue-50 hover:bg-blue-100 text-blue-700 font-mono text-[11px] font-semibold transition min-h-[40px]"
                  >
                    <Mail className="size-3.5" />
                    <span>Email</span>
                  </a>

                  <button
                    onClick={() => setSelectedLeadForSheet(lead)}
                    className="flex items-center justify-center gap-1.5 py-2 px-2 rounded-lg bg-neutral-100 hover:bg-neutral-200 text-slate-700 font-mono text-[11px] font-semibold transition min-h-[40px]"
                  >
                    <span>Details</span>
                    <ArrowUpRight className="size-3.5" />
                  </button>
                </div>
              </div>
            ))
          )}
        </div>

        {/* Desktop View: Full Data Table (Visible on sm: and up) */}
        <div className="hidden sm:block overflow-x-auto">
          <table className="w-full text-left text-xs font-inter">
            <thead className="bg-neutral-50 text-[10px] font-mono uppercase text-slate-500 border-b border-neutral-200">
              <tr>
                <th className="py-3 px-4 font-semibold">Contact Name</th>
                <th className="py-3 px-4 font-semibold">Email Address</th>
                <th className="py-3 px-4 font-semibold">Phone Number</th>
                <th className="py-3 px-4 font-semibold">Date Captured</th>
                <th className="py-3 px-4 font-semibold text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-neutral-100">
              {filteredLeads.length === 0 ? (
                <tr>
                  <td colSpan={5} className="py-12 text-center text-slate-400 font-mono text-xs">
                    No captured leads found matching query.
                  </td>
                </tr>
              ) : (
                filteredLeads.map((lead) => (
                  <tr
                    key={lead.id}
                    onClick={() => setSelectedLeadForSheet(lead)}
                    className="cursor-pointer hover:bg-blue-50/60 transition-colors group"
                  >
                    <td className="py-3.5 px-4 text-slate-900 font-semibold font-mono flex items-center gap-2">
                      <User className="size-4 text-blue-600 group-hover:scale-110 transition shrink-0" />
                      <span>{lead.name}</span>
                    </td>
                    <td className="py-3.5 px-4 text-slate-600">{lead.email}</td>
                    <td className="py-3.5 px-4 text-slate-600 font-mono">{lead.phone || "N/A"}</td>
                    <td className="py-3.5 px-4 text-slate-500 font-mono text-[11px]">{lead.date || "Today"}</td>
                    <td className="py-3.5 px-4 text-right">
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          setSelectedLeadForSheet(lead);
                        }}
                        className="text-xs font-mono text-blue-700 hover:text-blue-900 font-bold underline-offset-2 hover:underline min-h-[36px] px-2 py-1 inline-flex items-center"
                      >
                        View Transcript →
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Slide-Over Sheet Component for Lead Inspection */}
      <Sheet open={!!selectedLeadForSheet} onOpenChange={(open) => !open && setSelectedLeadForSheet(null)}>
        <SheetContent side="right" className="w-full sm:max-w-md bg-white p-4 sm:p-6 overflow-y-auto space-y-6">
          {selectedLeadForSheet && (
            <>
              <SheetHeader className="text-left space-y-2 border-b border-neutral-100 pb-4">
                <div className="flex items-center gap-2">
                  <span className="p-1.5 rounded bg-blue-50 border border-blue-100 text-blue-700 shrink-0">
                    <Sparkles className="size-4" />
                  </span>
                  <SheetTitle className="text-base font-mono font-bold text-slate-900">
                    Lead CRM Record & Transcript
                  </SheetTitle>
                </div>
                <SheetDescription className="text-xs text-slate-500 font-inter">
                  Captured via <strong className="text-slate-900">{selectedLeadForSheet.source || "AI Web Chat Concierge"}</strong>
                </SheetDescription>
              </SheetHeader>

              <div className="space-y-4 sm:space-y-5 text-xs font-inter">
                <div className="space-y-1.5 bg-neutral-50 rounded-lg p-3.5 sm:p-4 border border-neutral-200">
                  <span className="text-[10px] font-mono uppercase text-slate-400 font-bold">Contact Name</span>
                  <p className="text-sm sm:text-base font-bold font-mono text-slate-900">{selectedLeadForSheet.name}</p>
                </div>

                <div className="space-y-1.5">
                  <span className="text-[10px] font-mono uppercase text-slate-400 font-bold">Email Address</span>
                  <p className="text-slate-800 font-medium flex items-center gap-2 text-xs">
                    <Mail className="size-4 text-blue-600 shrink-0" />
                    <a href={`mailto:${selectedLeadForSheet.email}`} className="hover:underline text-blue-700 break-all">
                      {selectedLeadForSheet.email}
                    </a>
                  </p>
                </div>

                <div className="space-y-1.5">
                  <span className="text-[10px] font-mono uppercase text-slate-400 font-bold">Phone Number</span>
                  <p className="text-slate-800 font-mono flex items-center gap-2 text-xs">
                    <Phone className="size-4 text-blue-600 shrink-0" />
                    {selectedLeadForSheet.phone ? (
                      <a href={`tel:${selectedLeadForSheet.phone}`} className="hover:underline text-blue-700">
                        {selectedLeadForSheet.phone}
                      </a>
                    ) : (
                      "Unprovided"
                    )}
                  </p>
                </div>

                <div className="space-y-1.5">
                  <span className="text-[10px] font-mono uppercase text-slate-400 font-bold">AI Chat Inquiry Notes</span>
                  <div className="bg-neutral-50 rounded-lg border border-neutral-200 p-3.5 sm:p-4 text-slate-700 leading-relaxed text-xs">
                    {selectedLeadForSheet.notes || "Lead submitted inquiry regarding high-throughput custom web portal and AI concierge pricing models."}
                  </div>
                </div>

                {copiedNotice && (
                  <div className="p-3 bg-green-50 border border-green-200 text-green-800 rounded-lg font-mono text-xs flex items-center gap-2">
                    <CheckCircle2 className="size-4 text-green-600 shrink-0" />
                    <span>Contact details copied to clipboard!</span>
                  </div>
                )}
              </div>

              <SheetFooter className="pt-4 border-t border-neutral-100 flex flex-col sm:flex-row gap-2">
                <button
                  onClick={handleCopyData}
                  className="w-full sm:w-auto flex-1 py-2.5 px-4 rounded-lg border border-neutral-300 font-mono text-xs text-slate-700 hover:bg-neutral-50 flex items-center justify-center gap-2 min-h-[44px]"
                >
                  <Copy className="size-3.5" />
                  <span>Copy Record</span>
                </button>
                <a
                  href={`mailto:${selectedLeadForSheet.email}`}
                  className="w-full sm:w-auto flex-1 py-2.5 px-4 rounded-lg bg-blue-700 hover:bg-blue-800 text-white font-mono font-semibold text-xs flex items-center justify-center gap-2 min-h-[44px]"
                >
                  <Mail className="size-3.5" />
                  <span>Email Lead</span>
                </a>
              </SheetFooter>
            </>
          )}
        </SheetContent>
      </Sheet>
    </div>
  );
};

export default LeadsTab;
