"use client";

import React, { useState } from "react";
import { useDashboard } from "@/components/Dashboard/DashboardContext";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
  SheetFooter
} from "@/components/ui/sheet";
import {
  Inbox,
  Search,
  Mail,
  Phone,
  Calendar,
  User,
  ArrowUpRight,
  CheckCircle2,
  Shield,
  Copy,
  ExternalLink,
  Sparkles,
  Filter
} from "lucide-react";

const LeadsTab = () => {
  const { activeClient, role, leads } = useDashboard();
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedLeadForSheet, setSelectedLeadForSheet] = useState(null);
  const [copiedNotice, setCopiedNotice] = useState(false);

  const clientLeads = role === "client" 
    ? leads.filter((l) => l.clientSlug === activeClient?.slug)
    : leads.filter((l) => l.clientSlug === activeClient?.slug || activeClient?.slug === "egostix-internal");

  const filteredLeads = clientLeads.filter(
    (l) =>
      l.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      l.email.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const handleCopyData = () => {
    if (!selectedLeadForSheet) return;
    const text = `Name: ${selectedLeadForSheet.name}\nEmail: ${selectedLeadForSheet.email}\nPhone: ${selectedLeadForSheet.phone || 'N/A'}`;
    navigator.clipboard.writeText(text);
    setCopiedNotice(true);
    setTimeout(() => setCopiedNotice(false), 2500);
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-200">
      {/* Context Banner */}
      <div className="bg-white rounded-xl border border-neutral-200 p-6 flex flex-col md:flex-row md:items-center justify-between gap-6 shadow-sm">
        <div className="space-y-1.5">
          <div className="flex items-center gap-2">
            <span className="p-2 rounded-lg bg-blue-50 border border-blue-100 text-blue-700">
              <Inbox className="size-5" />
            </span>
            <h3 className="text-xl font-mono text-slate-900 font-bold">
              {role === "owner" ? "Global Lead Hub & CRM Pipeline" : "Captured Leads & Inbound Contact Requests"}
            </h3>
          </div>
          <p className="text-xs text-slate-600 max-w-2xl font-inter leading-relaxed">
            Automated lead qualification and CRM record sync generated by Egostix AI concierges and lead capture forms.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-xs font-mono font-bold bg-blue-50 text-blue-700 border border-blue-200 px-3 py-2 rounded-lg">
            Total Leads: {clientLeads.length}
          </span>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="bg-white rounded-xl border border-neutral-200 p-4 shadow-sm flex flex-col sm:flex-row items-center justify-between gap-4">
        <div className="relative flex-1 w-full">
          <Search className="absolute left-3.5 top-3 size-4 text-slate-400" />
          <input
            type="text"
            placeholder="Search leads by contact name or email address..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 rounded-lg border border-neutral-300 text-xs font-inter focus:border-blue-700 focus:outline-none min-h-[44px]"
          />
        </div>
        <span className="text-xs font-mono text-slate-500 shrink-0">
          Showing <strong className="text-slate-900">{filteredLeads.length}</strong> qualified contacts
        </span>
      </div>

      {/* Leads Table */}
      <div className="bg-white rounded-xl border border-neutral-200 shadow-sm overflow-hidden">
        <div className="p-4 border-b border-neutral-200 bg-neutral-50 flex items-center justify-between">
          <h4 className="text-xs font-mono font-bold text-slate-900 uppercase tracking-wider">
            Inbound Qualified Contact Records
          </h4>
          <span className="text-[10px] font-mono text-emerald-700 font-bold bg-emerald-50 border border-emerald-200 px-2.5 py-1 rounded-full">
            HubSpot / Salesforce Sync Active
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-inter">
            <thead className="bg-neutral-50 text-[10px] font-mono uppercase text-slate-500 border-b border-neutral-200">
              <tr>
                <th className="py-3 px-4 font-semibold">Contact Name</th>
                <th className="py-3 px-4 font-semibold">Email Address</th>
                <th className="py-3 px-4 font-semibold">Phone Number</th>
                <th className="py-3 px-4 font-semibold">Date Captured</th>
                <th className="py-3 px-4 font-semibold text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-neutral-100">
              {filteredLeads.length === 0 ? (
                <tr>
                  <td colSpan={5} className="py-12 text-center text-slate-400 font-mono text-xs">
                    No captured leads found matching query.
                  </td>
                </tr>
              ) : (
                filteredLeads.map((lead) => (
                  <tr
                    key={lead.id}
                    onClick={() => setSelectedLeadForSheet(lead)}
                    className="cursor-pointer hover:bg-blue-50/60 transition-colors group"
                  >
                    <td className="py-3.5 px-4 text-slate-900 font-semibold font-mono flex items-center gap-2">
                      <User className="size-4 text-blue-600 group-hover:scale-110 transition" />
                      <span>{lead.name}</span>
                    </td>
                    <td className="py-3.5 px-4 text-slate-600">{lead.email}</td>
                    <td className="py-3.5 px-4 text-slate-600 font-mono">{lead.phone || "N/A"}</td>
                    <td className="py-3.5 px-4 text-slate-500 font-mono text-[11px]">{lead.date || "Today"}</td>
                    <td className="py-3.5 px-4 text-right">
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          setSelectedLeadForSheet(lead);
                        }}
                        className="text-xs font-mono text-blue-700 hover:text-blue-900 font-bold underline-offset-2 hover:underline"
                      >
                        View Transcript →
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Slide-Over Sheet Component for Lead Inspection */}
      <Sheet open={!!selectedLeadForSheet} onOpenChange={(open) => !open && setSelectedLeadForSheet(null)}>
        <SheetContent side="right" className="w-full sm:max-w-md bg-white p-6 overflow-y-auto space-y-6">
          {selectedLeadForSheet && (
            <>
              <SheetHeader className="text-left space-y-2 border-b border-neutral-100 pb-4">
                <div className="flex items-center gap-2">
                  <span className="p-1.5 rounded bg-blue-50 border border-blue-100 text-blue-700">
                    <Sparkles className="size-4" />
                  </span>
                  <SheetTitle className="text-base font-mono font-bold text-slate-900">
                    Lead CRM Record & Transcript
                  </SheetTitle>
                </div>
                <SheetDescription className="text-xs text-slate-500 font-inter">
                  Captured via <strong className="text-slate-900">{selectedLeadForSheet.source || "AI Web Chat Concierge"}</strong>
                </SheetDescription>
              </SheetHeader>

              <div className="space-y-5 text-xs font-inter">
                <div className="space-y-1.5 bg-neutral-50 rounded-lg p-4 border border-neutral-200">
                  <span className="text-[10px] font-mono uppercase text-slate-400 font-bold">Contact Name</span>
                  <p className="text-base font-bold font-mono text-slate-900">{selectedLeadForSheet.name}</p>
                </div>

                <div className="space-y-1.5">
                  <span className="text-[10px] font-mono uppercase text-slate-400 font-bold">Email Address</span>
                  <p className="text-slate-800 font-medium flex items-center gap-2 text-xs">
                    <Mail className="size-4 text-blue-600" />
                    <a href={`mailto:${selectedLeadForSheet.email}`} className="hover:underline text-blue-700">
                      {selectedLeadForSheet.email}
                    </a>
                  </p>
                </div>

                <div className="space-y-1.5">
                  <span className="text-[10px] font-mono uppercase text-slate-400 font-bold">Phone Number</span>
                  <p className="text-slate-800 font-mono flex items-center gap-2 text-xs">
                    <Phone className="size-4 text-blue-600" />
                    {selectedLeadForSheet.phone || "Unprovided"}
                  </p>
                </div>

                <div className="space-y-1.5">
                  <span className="text-[10px] font-mono uppercase text-slate-400 font-bold">AI Chat Inquiry Notes</span>
                  <div className="bg-neutral-50 rounded-lg border border-neutral-200 p-4 text-slate-700 leading-relaxed text-xs">
                    {selectedLeadForSheet.notes || "Lead submitted inquiry regarding high-throughput custom web portal and AI concierge pricing models."}
                  </div>
                </div>

                {copiedNotice && (
                  <div className="p-3 bg-green-50 border border-green-200 text-green-800 rounded-lg font-mono text-xs flex items-center gap-2">
                    <CheckCircle2 className="size-4 text-green-600" />
                    <span>Contact details copied to clipboard!</span>
                  </div>
                )}
              </div>

              <SheetFooter className="pt-4 border-t border-neutral-100 flex flex-col sm:flex-row gap-2">
                <button
                  onClick={handleCopyData}
                  className="flex-1 py-2.5 px-4 rounded-lg border border-neutral-300 font-mono text-xs text-slate-700 hover:bg-neutral-50 flex items-center justify-center gap-2 min-h-[44px]"
                >
                  <Copy className="size-3.5" />
                  <span>Copy Record</span>
                </button>
                <a
                  href={`mailto:${selectedLeadForSheet.email}`}
                  className="flex-1 py-2.5 px-4 rounded-lg bg-blue-700 hover:bg-blue-800 text-white font-mono font-semibold text-xs flex items-center justify-center gap-2 min-h-[44px]"
                >
                  <Mail className="size-3.5" />
                  <span>Email Lead</span>
                </a>
              </SheetFooter>
            </>
          )}
        </SheetContent>
      </Sheet>
    </div>
  );
};

export default LeadsTab;
